# Link Collection
# Each link will appear as a card in the page. Following fields are allowed.
#   title   - Name of the link. i.e. LinkedIn (required)
#   url     - Actual link (required)
#   icon    - Icon to use in the card

[[links]]
title = ""
url = ""
icon = ""
